### ISSUE TITLE
NopCommerce 4.40 version update

### ISSUE THREAD

**Issue by nddsoft** [MarinaAndreeva/nopWatermark#7]
Hi,
Will you be making this plugin available for Nop 4.40?
Thank you.

**Comment by codeiskool** [comment]
Me too looking for update to 4.40

**Comment by MarinaAndreeva** [comment]
@nddsoft, @codeiskool, the plugin has just been ported to nopCommerce 4.40. Binaries can be downloaded on the [Releases](https://github.com/MarinaAndreeva/nopWatermark/releases) page.
